version: '3'

tasks:
  default:
    desc: show commands
    cmds:
      - task -l --sort none

  build:
    desc: build the container
    cmds:
      - docker compose build --no-cache --force-rm

  up:
    desc: start the container
    cmds:
      - docker compose up --watch --menu=false

  stop:
    desc: stop the container
    cmds:
      - docker compose stop

  down:
    desc: down the container
    cmds:
      - docker compose down --remove-orphans

  down-v:
    desc: down the container and volume
    cmds:
      - docker compose down --remove-orphans --volume

  destroy:
    desc: destroy the all image and volume
    cmds:
      - docker compose down --rmi all --volumes --remove-orphans

  ps:
    desc: ps the container
    cmds:
      - docker compose ps

  logs:
    desc: show docker logs
    cmds:
      - docker compose logs

  watch-logs:
    desc: watch docker logs
    cmds:
      - docker compose logs --follow

  build-frontend:
    desc: build frontend container only
    cmds:
      - docker compose build frontend --no-cache

  up-frontend:
    desc: start frontend container only
    cmds:
      - docker compose up frontend --watch

  logs-frontend:
    desc: show frontend logs
    cmds:
      - docker compose logs frontend

  logs-app:
    desc: show backend logs
    cmds:
      - docker compose logs app

  dev:
    desc: start full development environment
    cmds:
      - echo "🚀 Starting Koog Demo full stack development environment..."
      - docker compose up --watch --menu=false

  build-mcp:
    desc: build MCP server container only
    cmds:
      - docker compose build mcp-server --no-cache

  up-mcp:
    desc: start MCP server container only
    cmds:
      - docker compose up mcp-server --watch

  logs-mcp:
    desc: show MCP server logs
    cmds:
      - docker compose logs mcp-server

  test-mcp:
    desc: test MCP server functionality
    cmds:
      - echo "🧪 Testing MCP Server..."
      - echo '{"jsonrpc":"2.0","method":"initialize","id":1,"params":{"protocolVersion":"2025-03-26","capabilities":{},"clientInfo":{"name":"test","version":"1.0"}}}' | docker compose exec -T mcp-server sh -c "java -jar app.jar"
