spring:
  devtools:
    livereload:
      enabled: true
  application:
    name: koog-demo
  profiles:
    active: ${APP_ENV:dev}

weather:
  api:
    key: ${OPENWEATHER_API_KEY:}
    url: https://api.openweathermap.org/data/2.5/weather

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    org.springframework: ${LOG_LEVEL:WARN}
  structured:
    enabled: true
    format:
      console: ecs
      file: ecs
    json:
      add:
        application: koog-demo
        environment: ${APP_ENV:dev}
